logging:
  level:
    org.springframework: INFO
server:
  port: 8890
  servlet:
    context-path: /fish-club
spring:
  main:
    allow-circular-references: true
  custom:
    cors:
      allowedOrigins: http://localhost:*
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/fish_club_db
    username: COURSE_WORK_USER
    password: b5zB3k1D1
  liquibase:
    enabled: false
    change-log: db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true