logging:
  level:
    org.springframework: INFO
server:
  port: 8890
  servlet:
    context-path: /fish-club
spring:
  custom:
    cors:
      allowedOrigins: http://localhost:*
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fish_club_dev
    username: postgres
    password: 123
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true